version: '3.1'
services:

  web:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - API=http://10.10.17.194/2:80
    entrypoint: node
    command: [ "webserver.js","4000"]
    ports:
      - 4000:4000

  api1:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: node
    command: [ "apiserver.js","80"]
    ports:
      - 8080:80

  api2:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: node
    command: [ "apiserver.js","80"]
    ports:
      - 8090:80
    
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro